### ISSUE TITLE
does not build due mavenRepo method

### ISSUE THREAD

**Issue by davidmoten** [juherr/jASN1#1]
Using gradle 2.14:

```
A problem occurred evaluating root project 'jASN1'.
> Could not find method mavenRepo() for arguments [{name=bintray-juherr-asn1, url=http://dl.bintray.com/content/juherr/asn1}] on repository container.
```

The method `mavenRepo` was deprecated in gradle 1.8 and removed in gradle 2.0

**Comment by juherr** [comment]
Thank for the report.

The root goals of the project (which should be documented) were to provide a diff view (between releases) of the initial jASN1 project located on https://www.openmuc.org/asn1/ and to provide artifacts in bintray/jcenter.

If you check the project history, you'll see I've make only few changes and I'm not proud enough of them.
As I've never used the project for my own needs, I never updated it. That's why you have gradle problems.

BTW, I've just pushed a new branch which only contains files from openmuc releases https://github.com/juherr/jASN1/tree/mainstream and master should be reworked (some copy/paste from my initial commits).
 
Tell me if it is enough for your current needs or if I should take the time to finish what I had in my head 3 years ago :)

**Comment by vvnravikanth** [comment]
Hi juherr,
  I tried compilation with Android studio using gradle 2.14.
  Used your latest version posted at link https://github.com/juherr/jASN1/tree/mainstream
  I get the error below

Please let us know the recommended gradle version with which we can compile your code.

Thanks,
Ravikanth

**Comment by juherr** [comment]
@vvnravikanth 
As I said, I'm not the owner of the code.
The mainstream branch is just copy/paste from jASN1 official code releases.

Years ago, I made some changes to be able to release it into a maven repository (see commits in the master branch).

If you really need it, I can try to make new maven releases.

**Comment by vvnravikanth** [comment]
Dear Juherr,
    Thanks for your quick response. I really want to test the functionality of jASN1 but currently being blocked because of gradle issue.
Any help regarding the use of correct gradle version is highly appreciated.

Thanks,
Ravikanth

**Comment by juherr** [comment]
@vvnravikanth You can start by downloading an already compiled packaged here: https://www.openmuc.org/asn1/files/releases/jasn1-1.5.0.tgz

**Comment by juherr** [comment]
Guys, I reworked the repo and, except 1.5.0, all versions are deployed on https://bintray.com/juherr/asn1/jASN1
It should be available on jcenter soon too.

1.5.0 has too many and deep changes to be easily imported (it looks they forked bnotes which was a dependency before).

Feel free to propose a pull request with the 1.5.0 merge if you want.
